### PR TITLE
Front-End-33, -41, and -47: Added Viewable and Interactable PDF Viewing

### PR DESCRIPTION
**Pull request by GregoryGismondi**
This commit focuses on issues front-end-33, -41, and -47. 

## Functionality Added Within Commit:
- Imports react-pdf
- User can click on the folder icon to show (if it is not already open) or hide (if it is already open) PDF
- User can click on the other folder icon to switch PDF being displayed if the other PDF is currently being displayed
- Dynamic spacing of elements
- Clicking on PDF will flip to the next page or loop around to the first page if the PDF is at the last page
- Fixed all bugs relating to PDF viewing from initial commits

## Issues With Commit:
- ~~Currently, the two files being displayed are not part of any commits (they were .gitignore-ed), meaning that the files must added or different files must be selected~~ Fixes with the latest commits
- ~~Gray background does not extend to the bottom of the screen leaving a white block~~ Fixed with the latest commits
- Gray background is set as default for the **ENTIRE** webpage

## Success Case (from front-end-33):
- Can the user click on a file and will the PDF pop open on the screen?
     - Yes, the user can click on the folder icon and the PDF will appear on the screen
- Can the user close or open other PDF files (only one file will be viewable at a time) and parse through the current PDF?
     - Yes, the user can close the current PDF or open a different PDF, which will hide the current PDF visible
     - Yes, the user can click on the PDF to parse through it

### CODE REVIEW

**Comment by GregoryGismondi** [comment]
Fixed bug where switching PDFs would not reset the page number displayed

**Comment by GregoryGismondi** [comment]
Rewrote the function to be independent of which file was using it. A function for each file is no longer needed. Also merged the main changes into branch to deal with conflicts

**Comment by GregoryGismondi** [comment]
Fixed screen colour bug and large spacing at the bottom of the paper

**Comment by GregoryGismondi** [comment]
Added files that were safe to be pushed to the repo and removed all references to previous testing files

**Review by geraldyywang — COMMENTED** [review]
LGTM

**Pull request merged**
